/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GitHubHeatmap: typeof import('./src/components/my-ui/github-hatmap/GitHubHeatmap.vue')['default']
    MBTICharacterCard: typeof import('./src/components/my-ui/mbti/MBTICharacterCard.vue')['default']
    PlanGoalList: typeof import('./src/components/my-ui/plan-goal-list/PlanGoalList.vue')['default']
    ResizableDashedLabel: typeof import('./src/components/my-ui/resizable-dashed-label/ResizableDashedLabel.vue')['default']
    TechScroll: typeof import('./src/components/my-ui/tech-scroll/TechScroll.vue')['default']
    Tooltip: typeof import('./src/components/my-ui/tooltip/Tooltip.vue')['default']
    TooltipSlot: typeof import('./src/components/my-ui/tooltip/TooltipSlot.vue')['default']
  }
}
